version: "3"
services:
  apollo-portal:
    container_name: apollo-portal
    build: apollo-portal/
    image: apollo-portal
    ports:
      - 8070:8070
    volumes:
      - "/docker/apollo/logs/100003173:/opt/logs/100003173"
      - "/apollo-portal/config/apollo-env.properties:/apollo-portal/config/apollo-env.properties"
    environment:
      - spring_datasource_url=jdbc:mysql://xx.xx.xxx.xx:8306/ApolloPortalDB?characterEncoding=utf8
      - spring_datasource_username=xxx
      - spring_datasource_password=xxxxxx


    restart: always
